version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: Pokemon_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root123
      MYSQL_DATABASE: Pokemon_database
      MYSQL_USER: Andy
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:


#version: '3'
#services:
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - '9090:9090'
#    volumes:
#      - ./prometheus:/etc/prometheus
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    networks:
#      - monitoring
#
#  grafana:
#    image: grafana/grafana
#    ports:
#      - '4000:3000'
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
#    networks:
#      - monitoring
#
#networks:
#  monitoring:
#    driver: bridge